import type { Metadata } from "next";
import {  Poppins, Kaushan_Script } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navBar";
import InfoBar from "./components/infoBar";



const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const kaushanScript = Kaushan_Script({
  variable: "--font-kaushan-script",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${poppins.variable} ${kaushanScript.variable} antialiased`}
      >
        <NavBar />
        <InfoBar />
        {children}
      </body>
    </html>
  );
}
